version: '3.8'

services:
  api:
    build: .
    image: python-open-restaurant-api
    volumes:
      - .:/app
    ports:
      - 8008:8008
    environment:
      DATABASE_URL: postgresql://postgres:123456@db:5432/postgres
    depends_on:
      - postgresql

  postgresql:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5498:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres

volumes:
  postgres_data:
    driver: local
