services:
  postgresql:
    image: postgres:14
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgresql_data:/var/lib/postgresql/data/
    ports:
      - 5498:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres

  api:
    build: .
    image: python-open-restaurant-fastapi
    healthcheck:
      test: curl --fail http://localhost:8008 || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 8008:8008
    environment:
      DATABASE_URL: postgresql://postgres:123456@db:5432/postgres
    depends_on:
      - postgresql

volumes:
  postgresql_data:
    driver: local
