#!/bin/bash
git submodule update --init --remote
rebuild_venv=$1
rebuild_venv="${rebuild_venv:-0}"
source utility-repo-scripts/setup_python_app.sh \
	--debug=1 \
	--overwrite_vscode_settings=1 \
	--overwrite_vscode_launch=1 \
	--setup_version=2 \
	--rebuild_venv="$rebuild_venv" \
	--is_package=0 \
	--python_formatter=black \
	--python_linter=pylint \
	--python_testing_framework=pytest \
	--no_jq=0
