#!/bin/bash
git submodule update --init --remote --force
rebuild_venv=$1
rebuild_venv="${rebuild_venv:-0}"
source utility-repo-scripts/setup_python_app.sh \
	--debug=1 \
	--setup_version=2 \
	--rebuild_venv="$rebuild_venv" \
	--python_version=3.10 \
	--is_package=0 \
	--include_isort=1 \
	--python_formatter=black \
	--pylint_enabled=1 \
	--flake8_enabled=1 \
	--pydocstyle_enabled=0 \
	--pytest_enabled=1 \
	--unittest_enabled=0 \
	--overwrite_vscode_settings=1 \
	--overwrite_vscode_launch=1 \
	--overwrite_pre_commit_config=1 \
	--overwrite_pylintrc=1 \
	--overwrite_flake8=1 \
	--overwrite_pyproject_toml=1 \
	--line_length=125
