#!/bin/bash
git submodule update --init --remote --force
rebuild_venv=$1
rebuild_venv="${rebuild_venv:-0}"
source utility-repo-scripts/setup_python_app.sh \
	--package_manager="pip-tools" \
	--rebuild_venv="$rebuild_venv" \
	--python_version="3.10" \
	--include_isort \
	--python_formatter=black \
	--pylint_enabled \
	--flake8_enabled \
	--pytest_enabled \
	--overwrite_vscode_settings \
	--overwrite_vscode_launch \
	--overwrite_pre_commit_config \
	--overwrite_pylintrc \
	--overwrite_flake8 \
	--overwrite_pyproject_toml \
	--line_length=125
