"""Add Restaurant Dayta

Revision ID: 4096b5e1c05a
Revises: 11b40de5c0cb
Create Date: 2022-12-07 21:44:33.106323

"""
from sqlmodel import Session, create_engine, select

from app.csv_utils import csv_import
from app.db import api_settings, assemble_database_url
from app.models import Restaurant

# revision identifiers, used by Alembic.
revision = "4096b5e1c05a"
down_revision = "11b40de5c0cb"
branch_labels = None
depends_on = None

restaurants: list[Restaurant] = csv_import()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    engine = create_engine(assemble_database_url(api_settings, False))

    with Session(engine) as session:
        for restaurant in restaurants:
            session.add(restaurant)
        session.commit()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    engine = create_engine(assemble_database_url(api_settings, False))

    with Session(engine) as session:
        for restaurant in restaurants:
            statement = select(Restaurant).where(
                Restaurant.name == restaurant.name, Restaurant.weekday == restaurant.weekday
            )
            results = session.exec(statement)
            restaurant = results.one()
            session.delete(restaurant)
        session.commit()
    # ### end Alembic commands ###
